Docs 54 test
cobalthq/cobalt-product-public-docs pull request #133
Opened 2022-06-14 14:58 UTC by mjang-cobalt

2022-07-28 13:18 UTC, mike2jang commented on content/en/Cobalt_Core/Learn/_index.md
> +Some one-line summary
You need to say something else

2022-07-28 13:18 UTC, mike2jang approved these changes

2022-07-28 13:22 UTC, mike2jang requested changes
I need something else

2022-07-28 13:25 UTC, mike2jang commented on content/en/Cobalt_Core/Learn/aws_cloud_test.md
> +Some one-line summary
This is something else

2022-07-28 13:26 UTC, mike2jang approved these changes

2022-08-25 12:25 UTC, mjang commented on content/en/Cobalt_Core/Learn/pentest_tools.md
> +  Some one-line description
This is a test

2022-08-25 12:25 UTC, mjang commented on content/en/Cobalt_Core/Learn/pentest_tools.md
> +{{% pageinfo %}}
A second test

2022-08-25 12:29 UTC, mjang commented on content/en/Cobalt_Core/Onboarding/_index.md
> +---
A third test

2022-08-25 12:29 UTC, mjang requested changes
test

2022-12-14 20:02 UTC, ana-dashuk-cobalt approved these changes
@mjang-cobalt I see that it's a test PR. Approved.

2022-12-14 21:07 UTC, closed without merging