Secure Design Article
cobalthq/cobalt-product-public-docs pull request #192
Opened 2022-09-29 10:06 UTC by shadixit

Added Secure Design Article.

2022-09-29 19:06 UTC, mjang-cobalt requested changes
Our target reader is a developer who doesn't know enough about security. When they read content, their ideal is to "copy/paste" from the content into their code.

IMO, we need to start the reader with a reference and your discussion of [A04:2021 – Insecure Design](https://owasp.org/Top10/A04_2021-Insecure_Design/), so the reader knows that you're addressing an important problem.

@shadixit , your content suggests that you want to focus on SQL design, and that's great. In my comments, I'm going to ask you to add some SQL-specific advice. Example: when you mention "least privilege", I think "for who?" Could we even apply least privilege to the SQL admin?

In general, I'd like to see code samples, as well as more specific references to software. I've made some suggestions as a rewrite. Can you add some samples, such as the kinds of privileges that you'd avoid for regular (non-admin) SQL users?

2022-09-29 19:06 UTC, mjang-cobalt commented on content/en/BestPractices/SecureDesign.md
> +Since this was not anticipated during the design phase, there wasn’t any preventive control to avoid this. A secure design with an application firewall to protect any bot activity and a lockout mecha
```suggestion
### Scenario 3: Missing Rate Limits

In eCommerce, it's common to set up coupon codes. If you forget to include rate limits, you may see problems, including:

- Bots which try to brute force coupon codes
- Extra traffic, which can lead to performance issues

If you follow secure design practices, you could have planned:

- An application firewall to protect your system from bots and excessive traffic
- A lockout mechanism
- Access through a service like CloudFlare, which also sets rate limits
```

2022-09-29 19:06 UTC, mjang-cobalt commented on content/en/BestPractices/SecureDesign.md
> +- You can also follow [OpenSAMM](https://www.opensamm.org/) framework, an open-source framework for implementing a strategy for software security. This model can be applied organization-wide, for a s
```suggestion
## Prevention

To follow best practices for secure design, you should: 

- Collect security requirements
- Collect business requirements
- Budget resources needed to create and manage security requirements 
- For each feature, document use cases as well as abuse cases when you create user stories. 
- Highlight security concerns with other developers.
- Conduct threat modeling exercises.
 - Create a mitigation strategy to handle possible attack scenarios.
- Conduct secure design and architecture reviews, to highlight:
   - Flaws in existing architecture 
    - Enable solutions to create a robust design. 
- Create feedback loops for vulnerabilities identified:
   - During the testing
   - In the production environment 

These feedback loops can help to revise threat models over time. 

- You can also follow the open source [OpenSAMM](https://www.opensamm.org/) framework to create a software security strategy. 
```

2022-10-01 18:08 UTC, shadixit commented on content/en/BestPractices/SecureDesign.md
> +Secure design recommends the least privileges for application database users. Since the secure design practices were not followed during the planning phase, the application database user was granted
@mjang-cobalt  The idea presented here is about the application database user(not the overall database design) which connects to the only application database via application code, for example, the below connection strings in (.NET), the user `sa` has the highest privileges in the database(`sa` user in MSSQL is admin always).  In a secure design scenario, developers can create a different user in the database which has access to only an application's database.


````
<configuration>  
<connectionstrings>    
<add name="myConnectionString" connectionstring="Data Source=YourSqlServerInstanceName;Initial Catalog=DataBaseName;User ID=sa;Password=PasswordForSqlServer;" providername="System.Data.SqlClient"></add>  
</connectionstrings>
</configuration>

````
But here what I want to show is not about secure implementation,  there is a difference between secure implementation and secure design. The-  [A4 Secure Design](https://owasp.org/Top10/A04_2021-Insecure_Design/) is all about identifying the risk early in the development cycle and planning this in advance. 
Here what I want to show is developers have failed to anticipate the risk of using admin database users in the application because of which SQL injection compromised the full database and eventually the server, which ideally could have been contained only to the application database. 

Please let me know your thoughts.

2022-10-03 14:41 UTC, mjang-cobalt commented on content/en/BestPractices/SecureDesign.md
> +Secure design recommends the least privileges for application database users. Since the secure design practices were not followed during the planning phase, the application database user was granted
@shadixit , thanks for your feedback. It sounds like you want to expand on the concept of `least privilege`. I now realize that you mentioned `least privileges` in your original draft, and I apologize for ignoring that.

Also, I'm now thinking that your target reader is the developer architect, the person who can plan and implement "Secure Design". (And I think most developers who want to advance in their careers want this knowledge.)

If I'm hearing you correctly, you're thinking of the following scenario:

Full database, which consists of
- One or more application databases
- Another database, such as users

With least privilege in secure design, you recommend the following scenario

- Separate administrative users for each database. The architect limits the privileges of each administrative user to a single database. This protects other parts of the full database, as well as the operating system.

I think you can go further, and limit privileges for "regular" database users. But I'm not an expert on database user privileges.

Does this make sense?

2022-10-03 16:06 UTC, mjang-cobalt commented on content/en/BestPractices/SecureDesign.md
> +Secure design recommends the least privileges for application database users. Since the secure design practices were not followed during the planning phase, the application database user was granted
@shadixit , I've talked this over with Gisela -- she prefers your approach. I need to think about this a bit, how to reword your approach for readability. I'll add more comments "tomorrow" US Pacific Time

2022-10-03 16:58 UTC, shadixit commented on content/en/BestPractices/SecureDesign.md
> +Secure design recommends the least privileges for application database users. Since the secure design practices were not followed during the planning phase, the application database user was granted
Hi @mjang-cobalt, Thanks for the comments. I am looking forward to your thoughts.

2022-10-05 20:52 UTC, mjang-cobalt commented on content/en/BestPractices/SecureDesign.md
> +Secure design recommends the least privileges for application database users. Since the secure design practices were not followed during the planning phase, the application database user was granted
HI @shadixit inspired by https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html#least-privilege, I'm taking your content and emphasizing what's **not** secure design (and what is)

```suggestion
### Scenario 1: Database Users with Too Much Access

On some databases, administrators set up all accounts with administrative privileges. On such systems, attackers who exploit a database system vulnerability can: 

- Access to the complete database.
- Run operating system commands, which could compromise your servers. 

That is not a secure design.

Secure design recommends that you configure least privileges for application database users. To follow best practices for secure design:

- As suggested by the OWASP article on [SQL Injection Prevention](https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html#least-privilege), "start from the ground up."
  - Start with read-only access. Add privileges only when needed.
  - Limit privileges to SQL accounts to specific databases.

With secure design, you can limit the impact of SQL injection to the privileges of the compromised user 
```

2022-10-05 20:54 UTC, mjang-cobalt reviewed
@shadixit I've now completed my review of your proposed article, If you have more comments, we'll chat more! Otherwise, you're welcome to propose your own changes, or accept my suggestions.

2022-10-06 16:22 UTC, shadixit commented on content/en/BestPractices/SecureDesign.md
> +A detailed threat modelling could have pointed out this scenario where an application user could access superadmin account. The threat model could also have recommended the developers implement stron
@mjang-cobalt here, this looks fine.

2022-10-06 16:23 UTC, shadixit commented on content/en/BestPractices/SecureDesign.md
> +Since this was not anticipated during the design phase, there wasn’t any preventive control to avoid this. A secure design with an application firewall to protect any bot activity and a lockout mecha
@mjang-cobalt  this also looks fine.

2022-10-11 20:00 UTC, mjang-cobalt commented on content/en/BestPractices/SecureDesign.md
> +Secure design recommends the least privileges for application database users. Since the secure design practices were not followed during the planning phase, the application database user was granted
I've updated the suggestion accordingly.

2022-10-17 18:24 UTC, mjang-cobalt approved these changes
Thanks for accepting the changes! (via Slack DM)

2022-10-21 18:01 UTC, merged