Added Insecure Deserialisation Instructional Article
cobalthq/cobalt-product-public-docs pull request #204
Opened 2022-10-11 07:14 UTC by farid007

Added md file

## Changelog

### Added

| Page | Deploy Preview | Comment |
| ----- | ----- | ----- |
| [Name] | [Link] | [Comment] |

### Updated

| Page | Deploy Preview | Comment |
| ----- | ----- | ----- |
| [Name] | [Link] | [Comment] |

## Preview This Change

To see how this change looks in production, scroll down to **Deploy Preview**. Select the link that looks like `https://deploy-preview-<num>--cobalt-docs.netlify.app/`

## Variables

Help us support a “Write once, publish everywhere” single source of truth. If you see a line that looks like:

`{{ % asset-categories % }}`

You’ve found a [shortcode](https://gohugo.io/content-management/shortcodes/) that we include in multiple documents.

You’ll find the content of the shortcode in the following directory:

https://github.com/cobalthq/cobalt-product-public-docs/tree/main/layouts/shortcodes

That shortcode has the same base name as what you see in the PR, such as `asset-categories.html`.

2022-10-17 14:46 UTC, mjang-cobalt requested changes
Thanks so much for your submittal, @farid007!

In the future, I'd appreciate fewer blank lines between paragraphs. That made it more difficult to review your PR. 

I've made some suggestions for readability. Please let me know if this affects technical accuracy. 

Because I'm unsure about the logic of the article, I may need to review the content a second time.

Let me know if you have any questions. Thanks!

2022-10-17 14:46 UTC, mjang-cobalt commented on content/en/BestPractices/Insecure_Deserialization.md
> +
Please describe and include links to all CVEs

```suggestion
## Attack Scenarios

You may see deserialization is in Machine Learning. Review the following examples of related vulnerabilities:

- [Arbitrary code execution via Insecure YAML deserialization in Nvidia runx](https://huntr.dev/bounties/1-pypi-runx/)
- [Remote Code Execution via Insecure Deserialization in Telerik UI (CVE-2019-18935)](https://hackerone.com/reports/1174185)

We share other vulnerabilities for web applications:

- [Bitbucket Data Center - Java Deserialization Vulnerability In Hazelcast - CVE-2022-26133](https://jira.atlassian.com/browse/BSERV-13173)
- [Confluence Data Center - Java Deserialization Vulnerability In Hazelcast - CVE-2016-10750](https://jira.atlassian.com/browse/BSERV-13173)
- Direct deserialization of user-controlled data. Example: CVE-2019-10068
- Native vulnerabilities in libraries. Example: CVE-2020-1747 
- Improper deserialization of language agnostic methods like XML and JSON data. Example: CVE-2017-9805

In some cases, you can serialize data ito implement authorization and authentication. Consider the following code snippet from [MITRE](https://cwe.mitre.org/data/definitions/502.html):

```

2022-10-17 14:46 UTC, mjang-cobalt commented on content/en/BestPractices/Insecure_Deserialization.md
> +# Vulnerable Code Snippets
Also -- we need more info -- what lines in the code snippet are vulnerable?

```suggestion

In this scenario, serialized data authorizes a user. Errors or discrepancies raise an `AuthFail` exception. However, an attacker can use a Base64 encoded deserialization payload to that's triggered when an app parses the `AuthToken` token header.

## Vulnerable Code Snippets

```

2022-10-17 14:46 UTC, mjang-cobalt commented on content/en/BestPractices/Insecure_Deserialization.md
> +Again, the serialized data is read directly from the request body without any checks. Therefore, it can be exploited easily to gain Remote code execution by generating payloads with the following scr
This is all under the `## NodeJS` section, so this still looks like the "NodeJS example". (I think you need to set up a separate section, so you could link back to it.)

I'm not sure what you mean by ` generic message otherwise replies with the name of the user. `
- Are you saying that a "generic message" is different from a response with the name of the user? If so, we need separate sentences with explanations
  - What's an example of a generic message
  - What's an example of a response with the name of the user?

```suggestion
The server behaves in a similar fashion to the NodeJS example. It listens on port 5000. When a POST request is made to the endpoint, the server tries to decode and deserialize the data to extract a username.
If there are errors, the server responds with a generic message otherwise replies with the name of the user. 

Again, the serialized data is read directly from the request body without any checks. Therefore, it can be exploited easily to gain Remote code execution by generating payloads with the following script:
```

2022-10-17 14:46 UTC, mjang-cobalt commented on content/en/BestPractices/Insecure_Deserialization.md
> +```python
I'm guessing this is a duplicate line

````suggestion
```python
````

2022-10-17 14:46 UTC, mjang-cobalt commented on content/en/BestPractices/Insecure_Deserialization.md
> +The resulting output would be a payload, which when sent in the POST body would execute the respective command on the system.
- Can you include an example of the payload? 
- Can you specify the "respective command"?

I'd also revise this line:

```suggestion
The output, when sent in the POST, executes the <something> command on the system.
```

2022-10-17 14:46 UTC, mjang-cobalt commented on content/en/BestPractices/Insecure_Deserialization.md
> +- Never directly deserialize any user-controlled or untrusted data. For example, take the original code snippet:
"Mitigations" suggest that you have more than one solution. I see only one solution in your draft.

```suggestion
## Solution

Do not directly deserialize any user-controlled or untrusted data. For example, take the original code snippet:  
```

2022-10-17 14:46 UTC, mjang-cobalt commented on content/en/BestPractices/Insecure_Deserialization.md
> +-   In the case of Java applications, if you do need to implement the `serializable` interface due to inheritance, you can override the `readObject()` to prevent actual deserialization. Take the foll
How does this "indirectly deserialize any user-controlled or untrusted data"?
- Which line shows how data flows into the deserilization function?
- How do you "limit and check" all incoming and outgoing network activity?

```suggestion
 In the above example, data from request headers flow directly into the deserialization function, making it vulnerable. 

-   Run untrusted deserialization function inside a sandbox. For example, you can use [nsjail](https://github.com/google/nsjail).
-   Use deserialization methods like JSON, XML, and YAML that are language-agnostic.
-   Use updated libraries, to avoid known security bugs.
-   Limit and check all incoming and outgoing network activity from deserialization containers and servers.

If you're a Java developer, you may need to implement the `serializable` interface due to inheritance. You can override the `readObject()` to prevent actual deserialization. Take the following example from [Snyk](https://snyk.io/):

```

2022-10-17 14:46 UTC, mjang-cobalt commented on content/en/BestPractices/Insecure_Deserialization.md
> +- In the case of PHP applications, ue a safe, standard data interchange format such as `JSON` (via `json_decode()` and `json_encode()`) instead of `unserialize()` function, if you need to pass serial
```suggestion

If you're using PHP, you may need to pass serialized data to the user. In that case, don't use the `unserialize()` function. Use a safe standard data interchange format such as `JSON` (via `json_decode()` and `json_encode()`).
```

2022-10-20 06:55 UTC, farid007 commented
Hi @mjang-cobalt, I have updated the doc according to your recommendations. Can you please review the same and let me know if there are any further issues which need to be resolved?

2022-10-20 13:35 UTC, mjang-cobalt commented
> Hi @mjang-cobalt, I have updated the doc according to your recommendations. Can you please review the same and let me know if there are any further issues which need to be resolved?

Hi @farid007 . 

- I see you've accepted some of my suggested changes, thank you. When you checked my suggestions, I _assume_ that they still are technically correct. (You're welcome to change your mind.)
- I see that you haven't commented on a few of my suggestions, starting with https://github.com/cobalthq/cobalt-product-public-docs/pull/204/files#r997128408

Now that we've established the parameters for the article, I'm applying the [Vale Grammar Linter](https://github.com/cobalthq/cobalt-product-public-docs/blob/main/GrammarLinter.md) to your work, and will create further suggestions from that.

I apologize for this (coming) second round of comments. I had trouble reading your original draft, with the many extra lines that you included between paragraphs.

2022-10-20 20:11 UTC, mjang-cobalt requested changes
@farid007 I feel like I made a number of comments that you did not understand, and therefore ignored. 

I hope, if you have questions, that you're willing to discuss them.

2022-10-20 20:11 UTC, mjang-cobalt commented on content/en/BestPractices/Insecure_Deserialization.md
> +The most common use of deserialization in python is via the `pickle.loads()` function. Consider the following server code:
```suggestion
## Python

The most common use of deserialization in python is via the `pickle.loads()` function. Consider the following server code:
```

2022-10-21 09:17 UTC, farid007 commented on content/en/BestPractices/Insecure_Deserialization.md
> +$ curl -X POST http://127.0.0.1:5000/ -d "{'payload': 'gASVKQAAAAAAAACMBXBvc2l4lIwGc3lzdGVtlJOUjA50b3VjaCAvdG1wL1BvQ5SFlFKULg=='}"
Hi @mjang-cobalt, can you elaborate on this? I am not sure what does `non-identifying` payload actually mean?

2022-10-21 09:36 UTC, farid007 commented
Hi @mjang-cobalt thank you for catching me upto speed, and apologies for missing the initial suggestions. I have updated the document accordingly, except for one minor hiccup. Thank you for all the help.

2022-11-10 20:10 UTC, mjang-cobalt approved these changes
I apologize for the delay in my response. We still need references, @farid007. In the future, I suggest that you follow the tempate.md file for our base pattern. You can also examine our other Best Practices articles.

2022-11-10 20:10 UTC, mjang-cobalt commented on content/en/BestPractices/Insecure_Deserialization.md
> +- Improper deserialization of language agnostic methods like XML and JSON data. Example: CVE-2017-9805
Removing extra lines. Adding links to CVEs

```suggestion
You may see deserialization in Machine Learning. Review the following examples of related vulnerabilities:

- [Arbitrary code execution via Insecure YAML deserialization in Nvidia runx](https://huntr.dev/bounties/1-pypi-runx/)
- [Remote Code Execution via Insecure Deserialization in Telerik UI (CVE-2019-18935)](https://hackerone.com/reports/1174185)

We share other vulnerabilities for web applications:

- [Bitbucket Data Center - Java Deserialization Vulnerability In Hazelcast - CVE-2022-26133](https://jira.atlassian.com/browse/BSERV-13173)
- [Confluence Data Center - Java Deserialization Vulnerability In Hazelcast - CVE-2016-10750](https://jira.atlassian.com/browse/BSERV-13173)

We present more scenarios related to insecure deserialization in web applications:

- Direct deserialization of user-controlled data. Example: [CVE-2019-10068](https://nvd.nist.gov/vuln/detail/cve-2019-10068)
- Native vulnerabilities in libraries. Example: [CVE-2020-1747](https://nvd.nist.gov/vuln/detail/cve-2020-1747)
- Improper deserialization of language agnostic methods like XML and JSON data. Example: [CVE-2017-9805](https://nvd.nist.gov/vuln/detail/cve-2017-9805)
```

2022-11-10 20:10 UTC, mjang-cobalt commented on content/en/BestPractices/Insecure_Deserialization.md
> +$ curl -X POST http://127.0.0.1:5000/ -d "{'payload': 'gASVKQAAAAAAAACMBXBvc2l4lIwGc3lzdGVtlJOUjA50b3VjaCAvdG1wL1BvQ5SFlFKULg=='}"
Your payload looks like an API token. I don't want to even suggest that we're using such identifying information.

```suggestion
$ curl -X POST http://127.0.0.1:5000/ -d "{'payload': '<substitute your payload>'}"
```

2022-11-10 20:10 UTC, mjang-cobalt commented on content/en/BestPractices/Insecure_Deserialization.md
> +- If you're using PHP, you may need to pass serialized data to the user. In that case, don't use the `unserialize()` function. Use a safe standard data interchange format such as `JSON` (via `json_de
Do you have any reference information? 

You'll see in our other [Best Practices](https://developer.cobalt.io/bestpractices/) articles, others have provided appropriate references. I'd start with the relevant OWASP 2021 Top 10 entry.

2022-11-15 07:18 UTC, farid007 commented on content/en/BestPractices/Insecure_Deserialization.md
> +- If you're using PHP, you may need to pass serialized data to the user. In that case, don't use the `unserialize()` function. Use a safe standard data interchange format such as `JSON` (via `json_de
Hi @mjang-cobalt, as always, thanks for the feedback. I have made the changes, added the references and so on. I will be waiting for your feedback. Thank you for all the help and feedback 😀

2023-01-05 19:19 UTC, mjang-cobalt commented
Closing. Merged from a different PR.

2023-01-05 19:19 UTC, closed without merging