[DOCS-255] Anonymize or delete your account data
cobalthq/cobalt-product-public-docs pull request #239
Opened 2022-11-25 14:09 UTC by ana-dashuk-cobalt

## Changelog

@mjang-cobalt I decided to name this section "Protect Your Account Data" instead of "Request to Anonymize or Delete Your Account Data" because the section is located on the main Cobalt Account page. It may look discouraging if users see these instructions once they navigate to this section. We may change the location, suggestions are welcome.

### Added

| Page | Deploy Preview | Comment |
| ----- | ----- | ----- |
| Cobalt Account > Protect Your Personal Data | Link | |

## Preview This Change

To see how this change looks in production, scroll down to **Deploy Preview**. Select the link that looks like `https://deploy-preview-<num>--cobalt-docs.netlify.app/`

## Variables

Help us support a “Write once, publish everywhere” single source of truth. If you see a line that looks like:

`{{% asset-categories %}}`

You’ve found a [shortcode](https://gohugo.io/content-management/shortcodes/) that we include in multiple documents.

You’ll find the content of the shortcode in the following directory:

https://github.com/cobalthq/cobalt-product-public-docs/tree/main/layouts/shortcodes

That shortcode has the same base name as what you see in the PR, such as `asset-categories.html`.

## Checklist for PR Author

[ ] Did you check for broken links and alt text?

Be sure to check for broken links and Alt Text issues. We have a partially automated process,
as described in this section of our repository README:
[Test Links and Alt Attributes](https://github.com/cobalthq/cobalt-product-public-docs/blob/main/README.md#test-links-and-alt-attributes).

2022-11-28 14:11 UTC, mjang-cobalt requested changes
Do we even want to mention GDPR in this section? I don't see it in the original Zendesk article.

2022-11-29 11:00 UTC, ana-dashuk-cobalt commented on content/en/Platform Deep Dive/Cobalt Account/_index.md
> +<br>
@mjang-cobalt The article was reviewed by Apporwa Verma in a private G Doc, she confirmed that we delete or anonymize users in compliance with GDPR policies.

2022-11-29 13:03 UTC, mjang-cobalt commented on content/en/Platform Deep Dive/Cobalt Account/_index.md
> +<br>
Approving on that basis.

2022-11-29 13:04 UTC, mjang-cobalt approved these changes

2022-11-29 18:10 UTC, merged