Fixing categories typo in methodologies
cobalthq/cobalt-product-public-docs pull request #457
Opened 2023-12-11 21:40 UTC by molfinn

## Changelog

### Added

| Page | Deploy Preview | Comment |
| ----- | ----- | ----- |
| Name | Link | Comment |

### Updated

| Page | Deploy Preview | Comment |
| ----- | ----- | ----- |
| Name | Link | Comment |

## Preview This Change

To see how this change looks in production, scroll down to **Deploy Preview**. Select the link that looks like `https://deploy-preview-<num>--cobalt-docs.netlify.app/`

## Variables

Help us support a “Write once, publish everywhere” single source of truth. If you see a line that looks like:

`{{% asset-categories %}}`

You’ve found a [shortcode](https://gohugo.io/content-management/shortcodes/) that we include in multiple documents.

You’ll find the content of the shortcode in the following directory:

https://github.com/cobalthq/cobalt-product-public-docs/tree/main/layouts/shortcodes

That shortcode has the same base name as what you see in the PR, such as `asset-categories.html`.

## Checklist for PR Author

[ ] Did you check for broken links and alt text?

Be sure to check for broken links and Alt Text issues. We have a partially automated process,
as described in this section of our repository README:
[Test Links and Alt Attributes](https://github.com/cobalthq/cobalt-product-public-docs/blob/main/README.md#test-links-and-alt-attributes).

2023-12-11 21:59 UTC, reginandrade commented on content/en/Methodologies/_index.md
> +- [Desktop] (/methodologies/desktop/)
I think the space btwn ] and ( is causing this not to be rendered as a link, but rather plain text

2023-12-11 22:00 UTC, reginandrade requested changes
[Desktop] (/methodologies/desktop/)  i think should be:
[Desktop](/methodologies/desktop/)

2023-12-11 22:09 UTC, molfinn commented
@reginandrade i think I updated based on your feedback! I also had one more commit - to add the params to the Planning page.

2023-12-12 20:39 UTC, molfinn commented
Closing this pr. Work was merged in 458.

2023-12-12 20:39 UTC, closed without merging